config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'blogs/new'
  get 'blogs/index'
  get 'blogs/show'
  get 'static_pages/home'
  get 'static_pages/resume'
  root 'static_pages#home'
  get '/resume',    to: 'static_pages#resume'
  get '/blogs',     to: 'blogs#index'
  get 'new_blog',   to: 'blogs#new'
  post 'new_blog',  to: 'blogs#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :blogs  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token

  before_save :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


  # Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end


  private
    def downcase_email
      email.downcase!
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def new
    @blog = Blog.new
  end

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.published_at = Time.zone.now

    if @blog.save
      flash[:success] = "Blog Post Added!"
      redirect_to blogs_url
    end
  end

  private

    def blog_params
      params.require(:blog).permit(:title, :post)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] = '1' ? remember(@user) : forget(@user)
      redirect_to root_url
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Changes navbar link to 'active' if the link_path
  # is the current page
  def active_class(link_path)
    current_page?(link_path) ? "nav-item active" : "nav-item"
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper

  # Makes HTML in a blog post more pretty
  # TODO: Allow for code, underlines, etc... 
  # (and return the string instead of just printing)
  def make_html(post)
    # Replaces text for bold input
    if post =~ /(\*\*(.+)\*\*)/m
      post.gsub!($1, "<strong>#{$2}</strong>")
    end

    # Replaces text with code when surrounded by '\code\' tags
    if post =~ /(\\code\\(.+)\\code\\)/m
      post.gsub!($1, "<div class='jumbotron blog-sf'><pre><code>#{$2}</code></pre></div>")
    end
    simple_format(post, class: "blog-sf")
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers user in a persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged in user, if there is one
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user
        log_in user
        @current_user = user
      end
    end
  end


  def logged_in?
    !current_user.nil?
  end

  
  # Forgets a persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  
  # Logs out the current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/_blog.html.erb
<li class="list-group-item">
  <h2><%= link_to blog.title, blog %></h2>
  <h6>Published: <%= blog.published_at.strftime("%B %d, %Y") %></h6>
</li>

app/views/blogs/index.html.erb
<h1>Blog</h1>
<ul class="list-group" style="margin-left: 2.5%; width: 95vw;">
  <%= render @blogs %>
</ul>

app/views/blogs/new.html.erb
<h1>New Blog Post</h1>
<div class="container" style="width: 95vw;">
  <div class="center jumbotron bg-dark">
    <%= form_for(@blog) do |b| %>
      <%= b.label :title, style: 'color: white;' %>
      <%= b.text_field :title, class: 'form-control' %>

      <%= b.label :post, style: 'color: white;' %>
      <%= b.text_area :post, class: 'form-control', rows: 10 %>

      <%= b.submit "Create Post", class: 'btn btn-primary mt-2', style: "width: 100%; margin-bottom: -5%;" %>
    <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<h1 style="text-align: left; margin-left: 5%;"><%= @blog.title %></h1>
<h6 style="margin-left: 5%;">Published: <%= @blog.published_at.strftime("%B %d, %Y") %></h6>
<hr style="margin-left: 5%; width: 90vw;">
<%= make_html(@blog.post) %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Austin Adams", root_path, class: "navbar-brand mb-0 h1" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="<%= active_class(root_path) %>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="<%= active_class(resume_path) %>">
        <%= link_to "Resume", resume_path, class: "nav-link" %>
      </li>
      <li class="<%= active_class(blogs_path) %>">
        <%= link_to "Blog", blogs_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="<%= active_class(new_blog_path) %>">
          <%= link_to "New Blog", new_blog_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

    <% if logged_in? %>
      <div class="col-sm-2" style="padding: 0;">
        <%= link_to "Log Out", logout_path, method: :delete, 
                                            class: 'btn btn-primary',
                                            style: 'width: 100%;' %>
      </div>
    <% else %>
      <div class="col-sm-2" style="padding: 0;">
        <%= link_to "Log In", login_path, class: 'btn btn-primary', 
                                          style: 'width: 100%;' %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Austin Adams</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  


  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Welcome to the Personal Site of Austin Adams</h1>
<p style="text-align: center;">Please check back later for updates.</p>
<p style="text-align: center;">
  For now, you can check out my 
  <a href="https://github.com/caustinwadams">Github account</a>
  to see the coding projects I am currently working on.
</p>

app/views/static_pages/resume.html.erb
<h1>Austin's Resume</h1>

<h2 class="resume">Education</h2>
<p class="resume mb-0"><strong>University of Maryland, College Park</strong></p>
<p class="resume mb-0">Bachelor of Science, Mathematics and Computer Science (May 2017)</p>
<p class="resume">College Park Scholars Citation for Public Leadership (May 2014)</p>

<h2 class="resume">Personal Projects</h2>
<p class="resume">This is where I will list my personal projects.</p>

<h2 class="resume">Work Experience</h2>
<p class="resume">This is where I will list my work experience.</p>